### ISSUE TITLE
Compatibility with .NET 6

### ISSUE THREAD

**Issue by ALDamico** [MarvinKlein1508/BlazorInputTags#1]
There is no Nuget package compatible with .NET 6, forcing developers to upgarde to at least .NET 7.
IMO, a release targeting versions 5 and 6 wouldn't be a bad idea.

**Comment by MarvinKlein1508** [comment]
Hi,

please try v8.0.1 of this package.

**Comment by ALDamico** [comment]
Wow, that was quick. Thanks a lot!
